#!/usr/bin/python3
# COMP3311 20T3 Ass3 ... print name, year, ratings of top N movies

import sys
import psycopg2

from helpers import execute

# define any local helper functions here

# set up some globals
usage = "Usage: best [N]"

# process command-line args
argc = len(sys.argv)
if argc != 2:
    N = 10
else:
    N = int(sys.argv[1])

# manipulate database
try:
    sql = "SELECT rating, title, start_year FROM movies ORDER BY rating DESC, title ASC LIMIT %d" % N
    rows = run(sql)
    for row in rows:
        print(f"{row[0]} {row[1]} ({row[2]})")
except psycopg2.Error as err:
    print("DB error: ", err)
